name: testgame
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.37
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1 # Added Firebase Core for initialization
  cloud_firestore: ^5.6.2 # Added Cloud Firestore for database functionality
  google_sign_in: ^6.2.2  # Google Sign-In dependency
  mailer: ^6.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/boss.jpg
    - lib/assets/images/boss2.jpg
    - lib/assets/images/logo.png
    - lib/assets/images/google.png
    - lib/assets/audio/bgmusic.mp3
